// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5179.Robot2015;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DigitalInput liftLiftDownLimit;
    public static SpeedController liftVictorSPLift;
    public static SpeedController forkVictorSPRight;
    public static SpeedController forkVictorSPLeft;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        liftLiftDownLimit = new DigitalInput(0);
        LiveWindow.addSensor("Lift", "LiftDownLimit", liftLiftDownLimit);
        
        liftVictorSPLift = new Talon(2);
        LiveWindow.addActuator("Lift", "VictorSPLift", (Talon) liftVictorSPLift);
        
        forkVictorSPRight = new Talon(3);
        LiveWindow.addActuator("Fork", "VictorSPRight", (Talon) forkVictorSPRight);
        
        forkVictorSPLeft = new Talon(4);
        LiveWindow.addActuator("Fork", "VictorSPLeft", (Talon) forkVictorSPLeft);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
